### PR TITLE
Version upgrade

### PR DESCRIPTION
**Pull request by kicken**
Upgrade converse.js to v7.0.4 and electron to 11.2.3

### CODE REVIEW

**Comment by nick-denry** [comment]
Hi! 

Good work, thank you. The PR awaiting to be tested and reviewed.

**Comment by jcbrand** [comment]
Hi @kicken, thanks for your PR and the work you've put into it.

Before your recent commits, I created a branch where I updated to Converse 9, updated Electron and removed AngularJS.

See here: https://github.com/conversejs/converse-desktop/tree/jcbrand/update-converse-9

I'll try to see to what extent I can merged the work you've done here with my branch and then merge that to master.
Then I'll make new Converse and Converse Desktop releases.

**Comment by kicken** [comment]
Hi @jcbrand 

I did notice your branch when I was looking around after making all the latest updates, should have done that before hand I guess lol.  I've not yet had the chance, but I do intend to give your branch a try.

**Comment by jcbrand** [comment]
@kicken: It's basically ready for release. I'd love to be able to minimize the app to the desktop tray when closing it, but I haven't figured out yet how to do that. Perhaps you know?

**Comment by jcbrand** [comment]
@kicken: I've merged my branch and your minimize fix to master.

I then tried to update master to Electron 16, like in this branch, but there was an issue with electron-settings.

I ran into this issue: https://github.com/nathanbuchar/electron-settings/issues/133

Funnily enough, that ticket is marked closed but there is no fix the the issue :(

I've decided to stay with Electron 11 for now (unless you know of a fix to get Electron 16 working).

I think the time is ripe to make a 9.0.2 release of Converse and then a new desktop release.

I'll close this branch, since I didn't see anything that could easily be merged to master. Sorry about that and thanks for the effort.

**Comment by kicken** [comment]
@jcbrand I had managed the update to Electron 16 in the previous version, I will try and get the changes implemented in the new branch.

**Pull request closed without merging**
