### PR TITLE
Remember window size when minimizing or closing application

### PR DESCRIPTION
**Pull request by hutchisr**

### CODE REVIEW

**Comment by jcbrand** [comment]
LGTM. @kicken Are you happy with these changes? If so, feel free to merge.

**Comment by kicken** [comment]
Changes do not appear to work well with a maximized window (on windows 11 at least).  The window is not properly restored to a maximized state when re-opened.

**Comment by hutchisr** [comment]
Wont have a Windows machine to test for a couple days but could probably fix this by having is also save and restore mainWindow.isMaximized() state

**Comment by hutchisr** [comment]
Sorry for the long wait, I think this should handle dealing with the window being maximized. Also improved the experience with fullscreen mode on mac a bit.

**Pull request merged**
